// Minimal ABIs for frontend interaction
export const ERC20ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function transferFrom(address from, address to, uint256 amount) returns (bool)",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event Approval(address indexed owner, address indexed spender, uint256 value)",
];

export const LivingSpaceNFTABI = [
  "function MAX_SUPPLY() view returns (uint256)",
  "function totalSpaces() view returns (uint256)",
  "function remainingSpaces() view returns (uint256)",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function balanceOf(address owner) view returns (uint256)",
  "function getSpace(uint256 tokenId) view returns (tuple(uint256 id, string name, uint8 spaceType, uint8 status, uint256 value, uint256 createdAt, string metadataURI))",
  "function getSpacesByOwner(address owner) view returns (uint256[])",
  "function approve(address to, uint256 tokenId)",
  "function transferFrom(address from, address to, uint256 tokenId)",
  "function setApprovalForAll(address operator, bool approved)",
  "function isApprovedForAll(address owner, address operator) view returns (bool)",
  "function rentalListings(uint256 tokenId) view returns (uint256, address landlord, uint256 monthlyRent, uint256 deposit, uint256 minMonths, uint256 maxMonths, bool active)",
  "function rentals(uint256 rentalId) view returns (uint256 tokenId, address landlord, address tenant, uint256 monthlyRent, uint256 deposit, uint256 startTime, uint256 endTime, uint256 lastRentPaid, bool active)",
  "function nextRentalId() view returns (uint256)",
  "function getActiveRentalListings() view returns (uint256[])",
  "function listForRent(uint256 tokenId, uint256 monthlyRent, uint256 deposit, uint256 minMonths, uint256 maxMonths)",
  "function rentSpace(uint256 tokenId, uint256 months)",
  "function payRent(uint256 rentalId)",
  "function endRental(uint256 rentalId)",
  "event SpaceMinted(uint256 indexed tokenId, address indexed to, uint8 spaceType, uint256 value)",
  "event SpaceListedForRent(uint256 indexed tokenId, uint256 monthlyRent, uint256 deposit)",
  "event SpaceRented(uint256 indexed rentalId, uint256 indexed tokenId, address landlord, address tenant)",
  "event RentPaid(uint256 indexed rentalId, address tenant, uint256 amount)",
  "event RentalEnded(uint256 indexed rentalId, uint256 indexed tokenId)",
  "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
];

export const LivingSpaceMarketABI = [
  "function listings(uint256) view returns (uint256 tokenId, address seller, uint256 price, bool active, uint256 listedAt)",
  "function downPayments(uint256) view returns (uint256 tokenId, address buyer, uint256 totalPrice, uint256 amountPaid, uint256 deadline, bool completed, bool defaulted)",
  "function platformFeeBps() view returns (uint256)",
  "function getActiveListings() view returns (uint256[])",
  "function listSpace(uint256 tokenId, uint256 price)",
  "function delistSpace(uint256 tokenId)",
  "function buySpace(uint256 tokenId)",
  "function startDownPayment(uint256 tokenId, uint256 initialPayment, uint256 deadlineDays)",
  "function payInstallment(uint256 dpId, uint256 amount)",
  "function claimDefault(uint256 dpId)",
  "event SpaceListed(uint256 indexed tokenId, address indexed seller, uint256 price)",
  "event SpaceSold(uint256 indexed tokenId, address indexed buyer, uint256 price)",
  "event DownPaymentCreated(uint256 indexed dpId, uint256 indexed tokenId, address buyer, uint256 totalPrice, uint256 initialPayment)",
];

export const LendingPoolABI = [
  "function offers(uint256) view returns (uint256 id, address lender, uint256 amount, uint256 remainingAmount, uint256 interestRateBps, uint256 minDuration, uint256 maxDuration, bool active, uint256 createdAt)",
  "function loans(uint256) view returns (uint256 id, uint256 offerId, address borrower, address lender, uint256 principal, uint256 collateral, uint256 nftCollateral, uint256 interestRateBps, uint256 startTime, uint256 duration, uint256 interestAccrued, bool repaid, bool liquidated)",
  "function totalLent(address) view returns (uint256)",
  "function totalBorrowed(address) view returns (uint256)",
  "function collateralBalance(address) view returns (uint256)",
  "function nftLocked(uint256 tokenId) view returns (bool)",
  "function nftLtvBps() view returns (uint256)",
  "function nextOfferId() view returns (uint256)",
  "function nextLoanId() view returns (uint256)",
  "function totalPoolLiquidity() view returns (uint256)",
  "function calculateInterest(uint256 loanId) view returns (uint256)",
  "function depositCollateral(uint256 amount)",
  "function withdrawCollateral(uint256 amount)",
  "function createOffer(uint256 amount, uint256 interestRateBps, uint256 minDurationDays, uint256 maxDurationDays) returns (uint256)",
  "function cancelOffer(uint256 offerId)",
  "function borrow(uint256 offerId, uint256 amount, uint256 durationDays) returns (uint256)",
  "function borrowWithNFT(uint256 offerId, uint256 nftTokenId, uint256 durationDays) returns (uint256)",
  "function repayLoan(uint256 loanId)",
  "function liquidate(uint256 loanId)",
  "event OfferCreated(uint256 indexed offerId, address indexed lender, uint256 amount, uint256 interestRate)",
  "event LoanCreated(uint256 indexed loanId, uint256 indexed offerId, address borrower, uint256 principal, uint256 collateral)",
  "event NFTLoanCreated(uint256 indexed loanId, uint256 indexed offerId, address borrower, uint256 principal, uint256 nftTokenId)",
  "event LoanRepaid(uint256 indexed loanId, uint256 principal, uint256 interest)",
  "event NFTLiquidated(uint256 indexed loanId, address liquidator, uint256 nftTokenId)",
];

export const CompetitionManagerABI = [
  "function competitions(uint256) view returns (uint256 id, uint8 competitionType, uint8 status, string name, string description, uint256 entryFee, uint256 prizePool, uint256 maxParticipants, uint256 participantCount, address judge, address winner, uint8 rewardMode, uint256 stakedSpaceId, uint8 mintSpaceType, uint256 mintSpaceValue, uint256 startTime, uint256 endTime, uint256 createdAt)",
  "function nextCompetitionId() view returns (uint256)",
  "function isParticipant(uint256, address) view returns (bool)",
  "function getParticipants(uint256 compId) view returns (address[])",
  "function getCompetition(uint256 compId) view returns (tuple(uint256 id, uint8 competitionType, uint8 status, string name, string description, uint256 entryFee, uint256 prizePool, uint256 maxParticipants, uint256 participantCount, address judge, address winner, uint8 rewardMode, uint256 stakedSpaceId, uint8 mintSpaceType, uint256 mintSpaceValue, uint256 startTime, uint256 endTime, uint256 createdAt))",
  "function scores(uint256, address) view returns (uint256)",
  "function joinCompetition(uint256 compId)",
  "function startCompetition(uint256 compId)",
  "function submitScore(uint256 compId, address participant, uint256 score)",
  "function submitSolution(uint256 compId, string solution)",
  "function startJudging(uint256 compId)",
  "function declareWinner(uint256 compId, address winner)",
  "function cancelCompetition(uint256 compId)",
  "function createCompetitionMintReward(uint8 _type, string _name, string _description, uint256 _entryFee, uint256 _maxParticipants, address _judge, uint8 _spaceType, uint256 _spaceValue, uint256 _durationHours) returns (uint256)",
  "function createCompetitionStakedReward(uint8 _type, string _name, string _description, uint256 _entryFee, uint256 _maxParticipants, address _judge, uint256 _stakedSpaceId, uint256 _durationHours) returns (uint256)",
  "event CompetitionCreated(uint256 indexed id, uint8 competitionType, string name, uint256 entryFee)",
  "event ParticipantJoined(uint256 indexed id, address indexed participant)",
  "event WinnerDeclared(uint256 indexed id, address indexed winner, uint256 prize, uint256 spaceId)",
];

export const SwapBridgeABI = [
  "function swapOrders(uint256) view returns (uint256 id, address maker, address fromToken, address toToken, uint256 fromAmount, uint256 toAmount, bool filled, bool cancelled, uint256 createdAt)",
  "function bridgeRequests(uint256) view returns (uint256 id, address user, string fromChain, string toChain, address tokenAddress, uint256 amount, string status, uint256 createdAt)",
  "function nextSwapOrderId() view returns (uint256)",
  "function nextBridgeRequestId() view returns (uint256)",
  "function getSupportedTokens() view returns (address[])",
  "function createSwapOrder(address fromToken, address toToken, uint256 fromAmount, uint256 toAmount) returns (uint256)",
  "function fillSwapOrder(uint256 orderId)",
  "function cancelSwapOrder(uint256 orderId)",
  "function initiateBridge(string fromChain, string toChain, address tokenAddress, uint256 amount) returns (uint256)",
  "event SwapOrderCreated(uint256 indexed orderId, address indexed maker, address fromToken, address toToken, uint256 fromAmount, uint256 toAmount)",
  "event SwapOrderFilled(uint256 indexed orderId, address indexed taker)",
  "event BridgeInitiated(uint256 indexed requestId, address indexed user, string fromChain, string toChain, uint256 amount)",
];
